language: node_js
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools gulp
  - npm install
after_success:
  - gulp build
  - firebase deploy - project jamesehlycom - token $FIREBASE_TOKEN